### ISSUE TITLE
Flask-WTForms compatibility layer

### ISSUE THREAD

**Issue by justanr** [justanr/Flask-Transfer#3]
I had originally designed a Flask-WTForms compatibility layer for the validators. There's still traces of this, such as optionally turning off validation when calling `Transfer.save`. However, once I added the concept of passing metadata to the validators and didn't see a good of passing metadata to Flask-Transfer validators that end up living on a wtforms field.

Flask-Transfer _could_ provide a custom Form class with a modified `Form.validate_on_submit` that receives a metadata attribute. But I feel this may be overstepping Flask-Transfer's scope. This also involves injecting a class in between a validator and `BaseValidator` that intercepts the `__call__` and passes the correct attributes instead of `field, form`.

This _could_ be out of scope for this project and I'm open to creating a `Flask-WTF-Transfer` (or similar) project that mediates this. Just import the form and validators from there so they can live peacefully together rather than hacking something together that'll distract from Flask-Transfer's goal.

**Comment by Deathnerd** [comment]
I agree. I think this project should be concerned only with core functionality for uploads, which is handling the bytestream (however it is passed to Flask). You could take the Flask-Admin approach and have a contrib submodule where you provide your custom Form object and anything else you can think of.

If you're not familiar with what I'm referring to, for example you can access the SQLAlchemy modules in Flask-Admin by importing them through `from flask_admin.contrib.sqla import ModelView` (just for example). I feel this provides a good structure and a common entry point for further extensions unrelated to core functionality

**Comment by justanr** [comment]
I'm playing with a few things in my free time that actually make me more confident about including something like this. I didn't know this, but the `wtforms.Form.meta` attribute is intended to be used as a stash for other packages to pull information off of, as well as configuring how a Form acts. So, that alleviates the need to redefine a bunch of stuff in `Flask-WTF` just have a `validate_on_submit(metadata=my_meta)`.

So the idea would be to dependency inject a new BaseValidator into the MRO of the native validators that'll intercept validation calls and pull the needed information off and then continue validating as normal.

[Take a peek at the preliminary](https://github.com/justanr/Flask-Transfer/blob/wtf/flask_transfer/wtf.py)

I'm unsure if a we're big enough for `contrib` or `ext` package, but thinking towards the future doesn't hurt either. 

However, there's still the issue if this is something that should be provided here or not. I'm of two minds about it. On one hand, most people will end up using this with `flask-wtf` and that provides a method for validating passed data, and a compat layer can hook into alerting the user about a bad upload through the Flask-WTF/wtforms mechanisms.

On the other, I'm sure there's other cool stuff I could be busy implementing (or writing documentation and better tests).
