### ISSUE TITLE
Release 0.0.2?

### ISSUE THREAD

**Issue by Jaza** [justanr/Flask-Transfer#5]
Haven't been any changes to Flask-Transfer for a few months now, and there are a bunch of commits that aren't included in 0.0.1.

Would be great if a 0.0.2 release of Flask-Transfer could be made, so that these commits are included in a stable version.

**Comment by justanr** [comment]
The biggest hold out for me is docs. I can do a 0.0.2 release, probably early next week and then hopefully finish the docs and do a 0.1 release. There's not much to document but it's something I'd like to have -- especially since being an official Flask extension requires them.

**Comment by justanr** [comment]
@Jaza I just pushed out v0.1.0 to PyPI and here. Batter it as hard as you can and let me know what breaks or needs to be changed.
